Added symlink exercise

diff --git a/main/master-scripts/checkmain-master b/main/master-scripts/checkmain-master
--- a/main/master-scripts/checkmain-master
+++ b/main/master-scripts/checkmain-master
@@ -215,7 +215,7 @@ handle_answer() {
 			luc_correct_answers=$((luc_correct_answers+1))
 			break
 		elif [[ "$luc_processed_choice" == "0" ]]; then
-			echo "Your answer should be a number from 1 to 6."
+			echo "Your answer should be a number from 1 to ${#luc_answers[@]}."
 		else
 			break
 		fi
@@ -2530,6 +2530,43 @@ red_belt_exercise_find_cleanup() {
 }
 
 red_belt_exercise_intro_to_symlinks() {
+#	SOURCE_PATH="$LUS_HOME/red-belt/link/source"
+#	TARGET_PATH="$LUS_HOME/red-belt/link/target"
+#	if [ -L "$SOURCE_PATH" ]; then
+#		# Get the actual target of the symbolic link
+#		ACTUAL_TARGET=$(readlink "$SOURCE_PATH")
+#		EXIT_CODE=$? # Capture the exit code of readlink
+#
+#		if [ $EXIT_CODE -eq 0 ]; then
+#			# Compare the actual target with the expected target
+#			if [ "$ACTUAL_TARGET" = "$TARGET_PATH" ]; then
+#				echo "'$SOURCE_PATH' is a symbolic link and correctly points to '$TARGET_PATH'."
+#				good_work
+#			else
+#				echo "Almost there! '$SOURCE_PATH' is a symbolic link, but it points to '$ACTUAL_TARGET'."
+#				echo "It should point to '$TARGET_PATH'."
+#			fi
+#		else
+#			# This case might happen if readlink fails (e.g., a broken symlink, though -L usually handles existence)
+#			echo "Error: Could not determine what '$SOURCE_PATH' points to (readlink failed)."
+#			echo "Please check if the link is valid and points to an existing file."
+#		fi
+#	elif [ -f "$SOURCE_PATH" ]; then
+#		# Get inode numbers
+#		original_inode=$(ls -i "$SOURCE_PATH" 2>/dev/null | awk '{print $1}')
+#		link_inode=$(ls -i "$TARGET_PATH" 2>/dev/null | awk '{print $1}')
+#
+#		if [ "$TARGET_PATH" -eq "$SOURCE_PATH" ]; then
+#			echo "'$SOURCE_PATH' has the same inode number ($original_inode) as '$TARGET_PATH'."
+#			echo "This means you created a hard link, not a symbolic link."
+#		else
+#			echo "'$SOURCE_PATH' exists, but it's a regular file, not a symbolic link."
+#			echo "Remember to use 'ln -s' for symbolic links."
+#		fi
+#	else
+#		echo "'$SOURCE_PATH' does not exist."
+#		echo "Please ensure you create the link with the correct name and in the correct location."
+#	fi
 	keep_going
 }
 
